'use client'

import { useState } from 'react'
import { CalendarDays, CheckCircle2, ChevronRight, CookingPot, Grid2X2, Heart, KeyRound, Map, MessageSquare, Share2, Sparkles, SprayCan, Star, Tag, Users, Wifi, Wind, BriefcaseBusiness, X } from 'lucide-react'
import { listings } from '@/lib/mock'

const galleryImages = [
  'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85',
  'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85',
  'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85',
]

const amenities = [
  { label: 'Fast wifi', icon: Wifi },
  { label: 'Kitchen', icon: CookingPot },
  { label: 'Air conditioning', icon: Wind },
  { label: 'Dedicated workspace', icon: BriefcaseBusiness },
]

const reviewData = [
  { name: 'Sharanya', years: '7 years on Airbnb', date: '2 weeks ago', text: 'The stay was very amazing, very cost friendly, we were 14 people. Had a great time with bonfire and live Barbecue. Staff was very helpful.', avatar: 'https://i.pravatar.cc/100?img=47' },
  { name: 'Jasvinder', years: '6 years on Airbnb', date: 'September 2026', text: 'Suraj was our contact person. We never met or talked to karan. Suraj was friendly, responsible and arranged good food.', avatar: 'https://i.pravatar.cc/100?img=12' },
  { name: 'Yash', years: '6 years on Airbnb', date: 'May 2026', text: 'I had a truly wonderful stay! The property was exactly as described — clean, cozy, and thoughtfully maintained. The location was perfect, offering both peace and easy access to everything.', avatar: 'https://i.pravatar.cc/100?img=11' },
  { name: 'Rajesh', years: '6 years on Airbnb', date: 'July 2026', text: 'excellent and amazing staff excellent place enjoyed every bit of it', avatar: 'https://i.pravatar.cc/100?img=68' },
]

const calendarWeeks = [
  ['', '', '', '', '1', '2', '3'],
  ['4', '5', '6', '7', '8', '9', '10'],
  ['11', '12', '13', '14', '15', '16', '17'],
  ['18', '19', '20', '21', '22', '23', '24'],
  ['25', '26', '27', '28', '29', '30', '31'],
]

function CalendarMonth({ name, november = false }: { name: string; november?: boolean }) {
  const days = november ? [['1', '2', '3', '4', '5', '6', '7'], ['8', '9', '10', '11', '12', '13', '14'], ['15', '16', '17', '18', '19', '20', '21'], ['22', '23', '24', '25', '26', '27', '28'], ['29', '30', '', '', '', '', '']] : calendarWeeks
  return <div className="flex-1"><h3 className="text-center text-lg font-semibold">{name}</h3><div className="mt-5 grid grid-cols-7 gap-y-3 text-center text-sm"><div className="text-xs font-medium text-gray-500">S</div><div className="text-xs font-medium text-gray-500">M</div><div className="text-xs font-medium text-gray-500">T</div><div className="text-xs font-medium text-gray-500">W</div><div className="text-xs font-medium text-gray-500">T</div><div className="text-xs font-medium text-gray-500">F</div><div className="text-xs font-medium text-gray-500">S</div>{days.flat().map((day, index) => <div key={`${name}-${index}`} className={day === '16' || day === '18' ? 'mx-auto flex size-9 items-center justify-center rounded-full bg-[#222] text-white' : day && !november && Number(day) < 16 ? 'text-gray-300 line-through' : day === '17' ? 'bg-gray-100 py-2 text-[#222]' : 'py-2 text-[#222]'}>{day}</div>)}</div></div>
}

export default function RoomPage() {
  const [galleryOpen, setGalleryOpen] = useState(false)
  const [aboutOpen, setAboutOpen] = useState(false)
  const listing = listings[0]

  return <main className="min-h-screen bg-white px-5 pb-24 text-[#222] md:px-10">
    <header className="mx-auto flex max-w-[1280px] items-center justify-between py-5"><a href="/" className="text-2xl font-semibold tracking-tight text-[#FF385C]">airbnb</a><div className="hidden items-center rounded-full border border-gray-200 px-5 py-3 text-sm font-medium shadow-sm md:flex"><span>Anywhere</span><span className="mx-4 border-l border-gray-300 pl-4">Anytime</span><span className="mx-4 border-l border-gray-300 pl-4 text-gray-500">Add guests</span><button className="ml-4 rounded-full bg-[#FF385C] p-2 text-white" aria-label="Search"><CalendarDays size={16} /></button></div><div className="flex items-center gap-2"><a href="/" className="rounded-full px-4 py-2 text-sm font-semibold hover:bg-gray-100">Explore</a><button className="rounded-full p-3 hover:bg-gray-100" aria-label="Open menu"><Users size={18} /></button></div></header>
    <div className="mx-auto max-w-[1280px]">
      <div className="flex flex-col gap-2 py-3 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight md:text-5xl">{listing.title} in Chandigarh</h1><p className="mt-3 flex flex-wrap items-center gap-2 text-sm font-medium"><Star size={15} fill="currentColor" /> 4.9 · 16 reviews · Superhost · <span className="underline">Chandigarh, India</span></p></div><div className="flex items-center gap-1"><button className="flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold hover:bg-gray-100"><Share2 size={17} /> Share</button><button className="flex items-center gap-2 rounded-full px-3 py-2 text-sm font-semibold hover:bg-gray-100"><Heart size={17} /> Save</button></div></div>
      <section className="relative mt-5 grid h-[60vh] min-h-[420px] grid-cols-4 grid-rows-2 gap-2 overflow-hidden rounded-2xl" aria-label="Property photos"><img src={galleryImages[0]} alt="Bright living room" className="col-span-2 row-span-2 h-full w-full object-cover" />{galleryImages.slice(1).map((image, index) => <img key={image} src={image} alt={`Property view ${index + 2}`} className="h-full w-full object-cover" />)}<button onClick={() => setGalleryOpen(true)} className="absolute bottom-5 right-5 flex items-center gap-2 rounded-lg bg-white px-4 py-3 text-sm font-semibold shadow-md"><Grid2X2 size={16} /> Show all photos</button></section>
      <div className="mt-10 grid gap-12 lg:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]"><section>
        <h2 className="text-2xl font-semibold">Entire home in Chandigarh</h2><p className="mt-2 text-gray-600">15 guests · 6 bedrooms · 6 beds</p>
        <div className="my-8 flex items-center gap-4 border-y border-gray-200 py-6"><div className="flex size-14 items-center justify-center rounded-full bg-[#fce7f3] text-lg font-semibold">A</div><div><p className="font-semibold">Hosted by Aisha</p><p className="text-sm text-gray-600">Superhost · 5 years hosting</p></div><Sparkles className="ml-auto" size={24} /></div>
        <div className="border-b border-gray-200 pb-8"><h3 className="text-xl font-semibold">What this place offers</h3><div className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2">{amenities.map(({ label, icon: Icon }) => <div key={label} className="flex items-center gap-4"><Icon size={22} strokeWidth={1.5} /><span>{label}</span></div>)}</div></div>
        <section className="border-b border-gray-200 py-8"><h3 className="text-2xl font-semibold">About this space</h3><p className="mt-4 max-w-2xl leading-7">This 6-BHK nature retreat offers stunning lake &amp; valley views, with top attractions like Mall Road, Manki Point, &amp; Baptist Church just minutes away...</p><button onClick={() => setAboutOpen(true)} className="mt-4 flex items-center gap-1 font-semibold underline">Show more <ChevronRight className="size-4" /></button></section>
        <section className="border-b border-gray-200 py-10"><h3 className="text-2xl font-semibold">2 nights in Kasauli</h3><p className="mt-2 text-gray-500">16 Oct 2026 - 18 Oct 2026</p><div className="mt-8 flex gap-12"><CalendarMonth name="October 2026" /><CalendarMonth name="November 2026" november /></div><div className="mt-8 flex items-center justify-between"><span aria-label="Keyboard shortcuts">⌨</span><button className="text-sm font-semibold underline">Clear dates</button></div></section>
        <section className="border-b border-gray-200 py-10"><h3 className="flex items-center gap-2 text-2xl font-semibold"><Star className="size-6" fill="currentColor" /> 4.86 · 7 reviews</h3><div className="mt-10 grid grid-cols-2 gap-6 md:grid-cols-4 lg:grid-cols-7">{[['Overall rating', '5'], ['Cleanliness', '4.9'], ['Accuracy', '4.9'], ['Check-in', '4.9'], ['Communication', '4.1'], ['Location', '5.0'], ['Value', '4.9']].map(([label, rating], index) => { const Icon = [SprayCan, SprayCan, CheckCircle2, KeyRound, MessageSquare, Map, Tag][index]; return <div key={label} className="border-r border-gray-200 pr-4 last:border-0"><p className="text-sm font-medium">{label}</p><p className="mt-1 text-sm font-semibold">{rating}</p>{index === 0 ? <div className="mt-3 flex flex-col gap-1">{[1, 2, 3, 4, 5].map((bar) => <div key={bar} className={`h-1 rounded-full ${bar === 5 ? 'bg-[#222]' : 'bg-gray-200'}`} />)}</div> : <Icon className="mt-5 size-6" strokeWidth={1.5} />}</div> })}</div><div className="mt-10 grid grid-cols-1 gap-x-16 gap-y-10 md:grid-cols-2">{reviewData.map((review) => <article key={review.name}><div className="flex items-center gap-4"><img src={review.avatar} alt="" className="size-12 rounded-full object-cover" /><div><p className="font-semibold">{review.name}</p><p className="text-sm text-gray-500">{review.years}</p></div></div><p className="mt-4 text-sm"><span>★★★★★</span> · {review.date}</p><p className="mt-2 line-clamp-3 leading-6">{review.text}</p><button className="mt-2 font-semibold underline">Show more</button></article>)}</div></section>
      </section><aside className="lg:sticky lg:top-24 lg:h-fit"><div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-xl"><div className="flex items-baseline gap-2"><span className="text-gray-500 line-through">₹22,152</span><strong className="text-2xl">₹19,937</strong><span>night</span></div><div className="mt-6 overflow-hidden rounded-xl border border-gray-400"><div className="grid grid-cols-2 border-b border-gray-400"><label className="p-3 text-xs font-semibold uppercase">Check-in<input type="text" placeholder="Add date" className="mt-1 block w-full bg-transparent text-sm font-normal outline-none placeholder:text-gray-500" /></label><label className="border-l border-gray-400 p-3 text-xs font-semibold uppercase">Checkout<input type="text" placeholder="Add date" className="mt-1 block w-full bg-transparent text-sm font-normal outline-none placeholder:text-gray-500" /></label></div><label className="block p-3 text-xs font-semibold uppercase">Guests<select className="mt-1 block w-full bg-transparent text-sm font-normal outline-none"><option>1 guest</option><option>2 guests</option><option>15 guests</option></select></label></div><button className="mt-5 w-full rounded-lg bg-[#FF385C] py-4 font-semibold text-white">Check availability</button><p className="mt-4 text-center text-sm text-gray-500">You won't be charged yet</p></div></aside></div>
      {galleryOpen && <div className="fixed inset-0 z-50 overflow-y-auto bg-white p-5 md:p-12"><button onClick={() => setGalleryOpen(false)} className="mb-6 rounded-full border px-4 py-2 font-semibold">Close</button><div className="mx-auto grid max-w-5xl gap-3 md:grid-cols-2">{galleryImages.map((image, index) => <img key={image} src={image} alt={`Gallery photo ${index + 1}`} className="w-full rounded-xl object-cover" />)}</div></div>}
      {aboutOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4"><div className="relative max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-7 shadow-2xl md:p-9"><button onClick={() => setAboutOpen(false)} className="absolute left-6 top-6 rounded-full p-2 hover:bg-gray-100" aria-label="Close about this space"><X className="size-5" /></button><h2 className="mb-8 text-3xl font-semibold">About this space</h2><div className="space-y-3 leading-7"><p>◆This 6-BHK nature retreat offers stunning lake &amp; valley views, with top attractions like Mall Road, Manki Point, &amp; Baptist Church just minutes away.</p><p>◆The villa features a spacious living lounge with panoramic glass windows, perfect for soaking in hill views while enjoying indoor games like table tennis.</p><p>◆Each bedroom comes with a private balcony that opens up to tranquil mountain &amp; forest views.</p><p>◆The open terrace doubles as a charming dining area with scenic seating arrangements and a swing.</p><h3 className="pt-5 font-semibold">The space</h3><p>Embodying the essence of Atithi Devo Bhava, our elite 5-star team is devoted to providing guests with unparalleled care and attention.</p><h3 className="pt-5 font-semibold">◆ Bedroom-1 ◆</h3><p>One king-sized bed<br />Ensuite bathroom<br />330 sq.ft<br />Wooden interiors<br />Fan<br />42” TV<br />AC<br />Heater<br />Electric kettle<br />Window-side seating<br />Large glass windows<br />Wardrobe space<br />Attached balcony with seating</p></div></div></div>}
    </div>
  </main>
}
